# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RRuOw7YilPRcTdxkgJtEsrUDcstnAUW9
"""

import random

subjects = [
    "imran khan",
    "babar azam",
    "nawaz shhareef",
    "shehbaz shareef",
    "salman khan",
]

actions = [
    'Dance',
    'Jump',
    'Wink',
    'Prank',
    'Clap',
]

place_things = [
    'Slurp',
    'Wink',
    'Spin',
    'Giggle',
    'Dab'
]

while True:
    subject_choice = random.choice(subjects)
    action_choice = random.choice(actions)
    place_choice = random.choice(place_things)

    headline = f"Breaking News: {subject_choice} {action_choice} {place_choice}"
    print(headline)

    user_input = input("Do you want one more? yes/no: ").lower().strip()

    if user_input.startswith("n"):
        break
    elif user_input.startswith("y"):
        continue
    else:
        print("Invalid input, exiting...")
        break

